/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Modelo.modelo;

import javax.swing.*;
import java.util.Calendar;

import java.sql.*;
public class CrearCuenta extends javax.swing.JFrame {
    


    private java.sql.Connection getConnection() throws SQLException{
        return modelo.getInstance();
    }

    public void mostrarAnos(){
        int i;
        do{
            for (i = 2024; i >= 1930; i--) {
                VarAno.addItem(String.valueOf(i));
            }
        }while (i>=1930);
    }

    public void mostrarmes(){
        int i;
        do{
            for (i = 1; i <=12;i++){
                VarMes.addItem(String.valueOf(i));
            }
        }while(i<=11);
    }

    public void mostrardias(){
        int i;
        do{
            for (i = 1; i <=31;i++){
                VarDia.addItem(String.valueOf(i));
            }
        }while(i<=30);
    }



    public void add() throws SQLException {
        CrearCuenta regis = new CrearCuenta();
        Calendar Fecha = Calendar.getInstance();

        //Fecha actual
        int diaAc, mesAc, annoAc;
        //Fecha nacimiento
        int dia, mes, anio;
        String FechaCreacion, FechaNacimiento;

        dia = Integer.parseInt((String) VarDia.getSelectedItem());
        mes = Integer.parseInt((String) VarMes.getSelectedItem());
        anio = Integer.parseInt((String) VarAno.getSelectedItem());

        FechaNacimiento = anio + "-" + mes + "-" + dia;

        diaAc = Fecha.get(Calendar.DATE);
        mesAc = Fecha.get(Calendar.MONTH)+1;
        annoAc = Fecha.get(Calendar.YEAR);
        FechaCreacion= annoAc + "-" + mesAc + "-" + diaAc;

        //Saber si es menor de edad
        int diferenciaEdad = annoAc-anio;
        if (mesAc < mes || (mesAc == mes && diaAc < dia)) {
            diferenciaEdad--;
        }

        if (diferenciaEdad<18){
            avisoMenor avi = new avisoMenor();
            avi.setVisible(true);
            avi.setLocationRelativeTo(null);
        }else{




            Connection conn = getConnection();
             PreparedStatement ps = conn.prepareStatement("INSERT INTO clientes (TipoIdentificacion, NumeroIdentificacion, Nombres, Apellidos, Correo, FechaNacimiento, FechaCreacion, FechaModificacion) VALUES (?, ?, ?, ?, ?, ?, ?, ?)");
            ps.setString(1, (String) VarTDocu.getSelectedItem());
            ps.setString(2, VarNDocu.getText());
            ps.setString(3, VarName.getText());
            ps.setString(4, VarApellido.getText());
            ps.setString(5, VarEmail.getText());
            ps.setString(6, FechaNacimiento);
            ps.setString(7, FechaCreacion);
            ps.setString(8, FechaCreacion);
            int rowsAffected = ps.executeUpdate();

            if (rowsAffected > 0) {
                System.out.println("Se inserto");
            } else {
                System.out.println("No se inserto");
            }
             }

            Index view = new Index();
            view.setVisible(true);
            view.setLocationRelativeTo(null);
            this.setVisible(false);
        }


    
    public CrearCuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Regis = new javax.swing.JButton();
        VarName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        VarApellido = new javax.swing.JTextField();
        VarTDocu = new javax.swing.JComboBox<>();
        VarNDocu = new javax.swing.JTextField();
        VarEmail = new javax.swing.JTextField();
        VarAno = new javax.swing.JComboBox<>();
        VarMes = new javax.swing.JComboBox<>();
        VarDia = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Creemos tu cuenta :D");

        Regis.setText("Registrarse");
        Regis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    RegisActionPerformed(evt);
                } catch (SQLException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        jLabel2.setText("Nombres");

        jLabel3.setText("Apellidos");

        jLabel4.setText("Tipo de Documento");

        jLabel5.setText("Numero de documento");

        jLabel6.setText("Correo");

        jLabel7.setText("Fecha de nacimiento");

        VarTDocu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cedula", "Pasaporte"}));
        VarTDocu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarTDocuActionPerformed(evt);
            }
        });

        VarAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AÑO"}));
        VarAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VarAnoActionPerformed(evt);
            }
        });

        VarMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MES"}));

        VarDia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DIA"}));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(260, 260, 260)
                        .addComponent(Regis))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1)))
                .addGap(332, 332, 332))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VarName)
                    .addComponent(VarApellido)
                    .addComponent(VarTDocu, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(VarNDocu)
                    .addComponent(VarEmail)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(VarAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VarMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(VarDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(326, 326, 326))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(VarName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(VarApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(VarTDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(VarNDocu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(VarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(VarAno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VarMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VarDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Regis)
                .addGap(63, 63, 63))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegisActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {//GEN-FIRST:event_RegisActionPerformed

        add();

        
    }//GEN-LAST:event_RegisActionPerformed

    private void VarTDocuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VarTDocuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VarTDocuActionPerformed

    private void VarAnoActionPerformed(java.awt.event.ActionEvent evt) {
        /*for (int i = 2024; i >= 1930; i--) {
            VarAno.addItem(String.valueOf(i));
        }*/

    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearCuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearCuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Regis;
    public javax.swing.JComboBox<String> VarAno;
    public javax.swing.JTextField VarApellido;
    public javax.swing.JComboBox<String> VarDia;
    public javax.swing.JTextField VarEmail;
    public javax.swing.JComboBox<String> VarMes;
    public javax.swing.JTextField VarNDocu;
    public javax.swing.JTextField VarName;
    public javax.swing.JComboBox<String> VarTDocu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
